apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: starstruck-runnerdeploy # Runner name
spec:
  replicas: 2
  template:
    spec:
      # repository: thefriser/tf-kubernetes
      organization: starstruckcreative
      dockerMTU: 1400
      # labels:
      #   - thefriser-k8s # Label to reference in your workflow
      containers:
        - name: docker
          env:
            - name: DOCKER_GROUP_GID
              value: "1001"
